Repository DiamondLightSource/SynchWeb, pull requests merged in 2025-05, with the labels that each got.

#921 LIMS-1648: Only display auto proc program attachment files where deleted column is 0
  api/config_sample.php
  api/index.php
  api/src/Page/DC.php
  client/src/js/modules/dc/views/autointegration.js
  client/src/js/modules/dc/views/autoprocattachments.js
  client/src/js/modules/dc/views/dc.js
  client/src/js/modules/dc/views/dcbase.js
  client/src/js/modules/dc/views/downstream.js
  client/src/js/modules/dc/views/downstreamwrapper.js
Labels: improvement

#916 LIMS-1400: Remove logon stats page
  api/src/Database/Type/MySQL.php
  api/src/Page/Stats.php
  client/src/js/modules/blstats/models/logons.js
  client/src/js/modules/blstats/views/logon.js
  client/src/js/modules/blstats/views/stats.js
Labels: Ready to Release

#930 LIMS-1702: Rename Archive button to Download Zip
  client/src/js/modules/dc/components/auto-processing-job-details.vue
  client/src/js/modules/dc/views/downstreamwrapper.js
  client/src/js/templates/dc/dc_autoproc.html
  client/src/js/templates/dc/downstreamerror.html
Labels: Ready to Release

#925 LIMS-1694: Allow beamlines to disable user assignment of pucks
  api/config_sample.php
  api/index.php
  api/src/Controllers/AssignController.php
  api/tests/Controllers/AssignControllerTest.php
  client/src/js/modules/assign/views/assign.js
Labels: Ready to Release, Configuration Change

#926 LIMS-1687: Remove references to GridInfo.pixelsPerMicronX/Y
  api/docs/db/DataCollections.md
  api/docs/definitions/gridinfo.yaml
  api/docs/dist/spec.json
  api/src/Page/DC.php
Labels: Ready to Release

#927 LIMS-1664: Improvements to registered dewar and container pages
  api/src/Page/Shipment.php
  client/src/js/modules/shipment/views/containerregistry.js
  client/src/js/modules/shipment/views/dewarregistry.js
Labels: Ready to Release
