Repository DiamondLightSource/SynchWeb, pull requests merged in 2025-01, with the labels that each got.

#860 LIMS-1540: Remove references to summary pages/DB
  api/config_sample.php
  api/index.php
  api/src/Database/DatabaseConnectionFactory.php
  api/src/Database/DatabaseFactory.php
  api/src/Page/Summary.php
  client/src/js/app/components/navbar.vue
  client/src/js/app/layouts/main.vue
  client/src/js/app/router/router.js
  client/src/js/app/store/store.js
  client/src/js/modules/summary/collections/summaryresults.js
  client/src/js/modules/summary/models/summaryresult.js
  client/src/js/modules/summary/routes.js
  client/src/js/modules/summary/styles/_summary.scss
  client/src/js/modules/summary/utils/utils.js
  client/src/js/modules/summary/views/summary.vue
Labels: javascript, improvement, php, Ready to Release, Configuration Change

#839 LIMS-128: Add plate view to queue page
  api/src/Page/Imaging.php
  api/src/Page/Sample.php
  client/src/css/partials/_imaging.scss
  client/src/js/modules/imaging/views/queuecontainer.js
  client/src/js/modules/shipment/components/container-queue-wrapper.vue
  client/src/js/modules/shipment/router.js
  client/src/js/modules/shipment/routes.js
  client/src/js/modules/shipment/views/plate.js
  client/src/js/templates/imaging/queuecontainer.html
  client/src/js/views/search.js
Labels: Ready to Release

#881 LIMS-1066: Autofill UDC visit on dispatch form
  api/src/Page/Shipment.php
  client/src/js/modules/shipment/views/dispatch.js
Labels: Ready to Release

#883 LIMS-1528: Fix sorting on old summary page
  api/src/Page/Processing.php
  client/src/js/collections/datacollectionsforvisit.js
  client/src/js/models/datacollectionsforvisit.js
  client/src/js/modules/dc/routes.js
  client/src/js/modules/dc/views/summary.js
  client/src/js/templates/dc/summary.html
Labels: Ready to Release

#865 LIMS-1554: Add 'State' column to proposals list page
  api/config_sample.php
  api/index.php
  api/src/Page/Proposal.php
  client/src/js/app/components/navbar.vue
  client/src/js/modules/proposal/list.js
Labels: Ready to Release, Configuration Change

#887 LIMS-1590: Dont allow name editing for lab contacts when login is set
  api/src/Page/Contact.php
  client/src/js/modules/contact/views/viewcontact.js
  client/src/js/templates/contact/contactview.html
Labels: Ready to Release

#880 LIMS-1558: Add functionality for SMILES code for any sample
  client/src/js/modules/samples/views/view.js
  client/src/js/templates/samples/sample.html
Labels: Ready to Release

#852 LIMS-1490: Use callback URL for incoming dewars via shipping service
  api/src/Controllers/AuthenticationController.php
  api/src/Page/Shipment.php
  client/src/js/templates/shipment/shipment.html
Labels: Ready to Release

#874 LIMS-1570: Remove unused app file
  api/src/Page.php
  client/package-lock.json
  client/package.json
  client/src/js/app.js
  client/src/js/templates/header.html
  client/src/js/templates/login.html
  client/src/js/templates/sidebar.html
  client/src/js/vendor/flot/jquery.flot.min.js
  client/src/js/vendor/flot/jquery.flot.min.js_.js
  client/src/js/vendor/flot/jquery.flot.tooltip.js
  client/src/js/vendor/highmaps/data.js
  client/src/js/vendor/highmaps/highmaps.js
  client/src/js/vendor/highmaps/world.js
  client/src/js/vendor/jquery/jquery-ui.min.js_options.js
  client/src/js/vendor/jquery/jquery-ui.timepicker-addon.js
  client/src/js/vendor/markdown.js
  client/src/js/vendor/modernizr.js
  client/src/js/vendor/require/require.js
  client/src/js/vendor/vue/polyfill.min.js
  client/src/js/views/header.js
  client/src/js/views/login.js
  client/src/js/views/sidebar.js
Labels: javascript, improvement, Ready to Release

#876 LIMS-1537: Add more options to reprocessing
  client/src/js/modules/dc/views/reprocess2.js
  client/src/js/modules/mc/views/datacollections.js
  client/src/js/templates/dc/reprocess.html
  client/src/js/templates/dc/reprocess_dc.html
  client/src/js/templates/mc/datacollections.html
Labels: Ready to Release

#891 LIMS-1466: Disable dispatch form validation when using the shipping service
  client/src/js/modules/shipment/models/dispatch.js
  client/src/js/modules/shipment/views/dispatch.js
Labels: Ready to Release
