Repository DiamondLightSource/SynchWeb, pull requests merged in 2025-03, with the labels that each got.

#910 LIMS-1646: Show 'Use Facility Account' button for EU dewar dispatch
  client/src/js/modules/shipment/views/dispatch.js
Labels: Ready to Release, Configuration Change

#896 LIMS-1496: Fix offset grid scan heatmaps in Safari
  client/src/js/modules/dc/views/gridplot.js
Labels: Ready to Release

#901 LIMS-1389 - Add upload to ccp4 cloud button
  api/config_sample.php
  api/index.php
  api/src/Page/Processing.php
  client/src/css/partials/_utility.scss
  client/src/js/modules/dc/views/attachments.js
  client/src/js/modules/dc/views/autointegration.js
  client/src/js/modules/dc/views/autoprocattachments.js
  client/src/js/templates/dc/cloudupload.html
  client/src/js/views/cloudupload.js
Labels: Ready to Release, Configuration Change

#908 LIMS-538: Remove the 'Centring Method' column from creating an MX container
  api/src/Page/Sample.php
  client/src/js/app/store/modules/store.samples.js
  client/src/js/modules/types/mx/samples/mx-puck-samples-table.vue
  client/src/js/modules/types/mx/samples/sample-table-mixin.js
  client/src/js/modules/types/mx/samples/tabbed-columns-view.vue
  client/src/js/modules/types/mx/shipment/views/container-mixin.js
  client/src/js/modules/types/mx/shipment/views/mx-container-add.vue
  client/src/js/utils/experimentkinds.js
Labels: Ready to Release

#900 LIMS-128: Add plate view to queue container page
  api/src/Page/Sample.php
  client/src/css/partials/_imaging.scss
  client/src/js/modules/imaging/views/queuecontainer.js
  client/src/js/modules/shipment/views/plate.js
  client/src/js/templates/imaging/queuecontainer.html
Labels: Ready to Release

#912 LIMS-1632: Buttons to go to next & previous puck in dewar
  client/src/js/app/components/page-title-header.vue
  client/src/js/app/components/prev-next-btngroup.vue
  client/src/js/modules/types/mx/shipment/views/mx-container-view.vue
Labels: enhancement, javascript

#888 LIMS-1406: Don't allow the location to be changed during a dispatch request
  client/src/js/templates/shipment/dispatch.html
Labels: Ready to Release
